// Code generated by protoc-gen-terraform. DO NOT EDIT.
// versions:
// 	 protoc-gen-gotf local
// 	 protoc          local
// source: local

package providerpb

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/travix/gotf/cntxt"
	"github.com/travix/gotf/rsrc"
	"google.golang.org/grpc"

	pb "github.com/travix/protoc-gen-gotf/example/pb"
)

// Ensure *GroupResource fully satisfy terraform framework interfaces.
var _ resource.Resource = &GroupResource{}
const GroupResource_client = cntxt.Key("client")

type GroupResource struct {
	proxy  rsrc.Resource
	client pb.GroupServiceClient // defined in proto file
}

func NewGroupResource(proxy rsrc.Resource) func() resource.Resource {
	if proxy == nil {
		panic("github.com/travix/gotf/rsrc.Resource is required")
	}
	return func() resource.Resource {
		return &GroupResource{proxy: proxy}
	}
}

func (r *GroupResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_group"
	if _proxy, ok := r.proxy.(rsrc.CanMetadata); ok {
		ctx = r.setupContext(ctx)
		_proxy.Metadata(ctx, req, resp)
	}
}

func (r *GroupResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "terraform resource",
		Attributes:          (&pb.Group{}).ResourceSchema(),
	}
	if _proxy, ok := r.proxy.(rsrc.CanSchema); ok {
		ctx = r.setupContext(ctx)
		_proxy.Schema(ctx, req, resp)
	}
}

func (r *GroupResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Get the gRPC client connection from the ProviderData
	if req.ProviderData == nil {
		resp.Diagnostics.AddError("Expected ProviderData to be not nil", "req.ProviderData is nil")
		return
	}
	conn, ok := req.ProviderData.(grpc.ClientConnInterface)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected ProviderData Type",
			fmt.Sprintf("Expected grpc.ClientConnInterface, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	// Create the service clients
	r.client = pb.NewGroupServiceClient(conn)
	if _proxy, ok := r.proxy.(rsrc.CanConfigure); ok {
		ctx = r.setupContext(ctx)
		_proxy.Configure(ctx, req, resp)
		return
	}
}

func (r *GroupResource) ConfigValidators(ctx context.Context) []resource.ConfigValidator {
	if _proxy, ok := r.proxy.(rsrc.CanConfigValidators); ok {
		ctx = r.setupContext(ctx)
		return _proxy.ConfigValidators(ctx)
	}
	tflog.Warn(ctx, "ConfigValidators method not implemented.Make sure argument to NewGroupResource() implements rsrc.CanConfigValidators interface")
	return nil
}

func (r *GroupResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	if _proxy, ok := r.proxy.(rsrc.CanValidateConfig); ok {
		ctx = r.setupContext(ctx)
		_proxy.ValidateConfig(ctx, req, resp)
		return
	}
	tflog.Warn(ctx, "ValidateConfig method not implemented.Make sure argument to NewGroupResource() implements rsrc.CanValidateConfig interface")
}

func (r *GroupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	if _proxy, ok := r.proxy.(rsrc.CanImportState); ok {
		ctx = r.setupContext(ctx)
		_proxy.ImportState(ctx, req, resp)
		return
	}
	tflog.Warn(ctx, "ImportState method not implemented.Make sure argument to NewGroupResource() implements rsrc.CanImportState interface")
}

func (r *GroupResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if _proxy, ok := r.proxy.(rsrc.CanModifyPlan); ok {
		ctx = r.setupContext(ctx)
		_proxy.ModifyPlan(ctx, req, resp)
		return
	}
	tflog.Warn(ctx, "ModifyPlan method not implemented.Make sure argument to NewGroupResource() implements rsrc.CanModifyPlan interface")
}

func (r *GroupResource) UpgradeState(ctx context.Context) map[int64]resource.StateUpgrader {
	if _proxy, ok := r.proxy.(rsrc.CanUpgradeState); ok {
		ctx = r.setupContext(ctx)
		return _proxy.UpgradeState(ctx)
	}
	tflog.Warn(ctx, "UpgradeState method not implemented.Make sure argument to NewGroupResource() implements rsrc.CanUpgradeState interface")
	return nil
}

func (r *GroupResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data pb.Group
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx = r.setupContext(ctx)
	diagnostics := r.proxy.Read(ctx, req, resp, &data)
	resp.Diagnostics.Append(diagnostics...)
}

func (r *GroupResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data pb.Group
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx = r.setupContext(ctx)
	diagnostics := r.proxy.Create(ctx, req, resp, &data)
	if diagnostics.HasError() {
		resp.Diagnostics.Append(diagnostics...)
		return
	}
	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *GroupResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data pb.Group
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx = r.setupContext(ctx)
	diagnostics := r.proxy.Update(ctx, req, resp, &data)
	if diagnostics.HasError() {
		resp.Diagnostics.Append(diagnostics...)
		return
	}
	// Save data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *GroupResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data pb.Group
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	ctx = r.setupContext(ctx)
	diagnostics := r.proxy.Delete(ctx, req, resp, &data)
	resp.Diagnostics.Append(diagnostics...)
}

func (r *GroupResource) setupContext(ctx context.Context) context.Context {
	// Pass members via context
	// also passes the service clients
	ctx = cntxt.WithValue(ctx, "client", r.client)
	return ctx
}
